version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: ..\log\app.log
    encoding: utf-8
    mode: a
  
  error:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: ..\log\errors.log
    encoding: utf-8
    mode: a

loggers:
  all_info_logger:
    level: DEBUG
    handlers: [file]
    propagate: false
  
  error_logger:
    level: WARNING
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [file]