file:
  - filename: 'Microsoft Access База данных.accdb'
    path_from: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Microsoft Access База данных.accdb'
    path_to: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Database\Microsoft Access База данных.accdb'
    file_size_before_B: '495616'
    new_file_name: 'None'
    file_modification_time_before: '1771676338.2686853'

  - filename: 'Документ Microsoft Publisher.pub'
    path_from: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Документ Microsoft Publisher.pub'
    path_to: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Ebooks\Документ Microsoft Publisher.pub'
    file_size_before_B: '59904'
    new_file_name: 'None'
    file_modification_time_before: '1771754898.5972114'

  - filename: 'Новый текстовый документ.txt'
    path_from: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Новый текстовый документ.txt'
    path_to: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Documents\Новый текстовый документ.txt'
    file_size_before_B: '0'
    new_file_name: 'None'
    file_modification_time_before: '1771755520.1398957'

  - filename: 'Новый текстовый документ.txt'
    path_from: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\nested_folder\Новый текстовый документ.txt'
    path_to: 'E:\work\All_Projects\File-OrganizerNew\test\test_folder2\Documents\Новый текстовый документ_1.txt'
    file_size_before_B: '17850'
    new_file_name: 'Новый текстовый документ_1.txt'
    file_modification_time_before: '1771754915.685585'
